### ISSUE TITLE
Can't run ResNet-12 experiments

### ISSUE THREAD

**Issue by ahmetius** [chrysts/dsn_fewshot#1]
Hi, 

After downloading the datasets as suggested in the README file, I cannot run the ResNet-12 experiments (Conv4 experiments do run however).

Here are the commands and the output I get:

`python3 train.py --train-shot 15 --head Subspace --network ResNet --dataset miniImageNet --eps 0.1`

Loading mini ImageNet dataset - phase trainval
Traceback (most recent call last):
  File "/home/src/dsn_fewshot/Resnet12/data/mini_imagenet.py", line 45, in load_data
    with open(file, 'rb') as fo:
FileNotFoundError: [Errno 2] No such file or directory: '/home/mini-imagenet/miniImageNet_category_split_train_phase_train.pickle'

`python3 train.py --train-shot 15 --head Subspace --network ResNet --dataset tieredImageNet --eps 0.1`
Loading tiered ImageNet dataset - phase train
Traceback (most recent call last):
  File "train.py", line 135, in <module>
    (dataset_train, dataset_val, data_loader) = get_dataset(opt)
  File "train.py", line 83, in get_dataset
    dataset_train = tieredImageNet(phase='train')
  File "/home/src/dsn_fewshot/Resnet12/data/tiered_imagenet.py", line 100, in __init__
    self.labels = data_train['labels']
KeyError: 'labels'

Which copies of mini-imagenet and tiered-imagenet have you used for your ResNet-12 experiments? The Mini-Imagenet dataset that you have pointed in the README does not contain any pickle files.

**Comment by chrysts** [comment]
Hi ahmetius,

Thanks for reaching out. Yes, I made a mistake about the dataset on the readme file.
I have changed the readme file to download the correct datasets for both mini-ImageNet and Tiered-ImageNet.

mini-ImageNet: https://drive.google.com/file/d/1fJAK5WZTjerW7EWHHQAR9pRJVNg1T1Y7
Tiered-ImageNet: https://drive.google.com/file/d/1nVGCTd9ttULRXFezh4xILQ9lUkg0WZCG

Please let me know if you still face the problem.

**Comment by ahmetius** [comment]
Hi,

Thank you for the quick reply. I face a different problem now. I run the training script with 4 GPUs (each with 16GB memory), however I get :

  File "train.py", line 240, in <module>
    loss.backward()
RuntimeError: CUDA out of memory 

The code will only run if I use 7 GPUs at once. Is that expected?

Best regards

**Comment by chrysts** [comment]
In our experiments, we used 4 GPUs on mini-ImageNet. 
I think you need to adjust the number of training images (shot) or testing images (query).
The setting for 4 GPUs is 5 train-way, 15 train-shot, and 6 train-query. 
So the total number of samples per episode is 15*5 + 6*5. 
But feel free to change the number of queries, it should be alright. 

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
I set the default value 10  in the code.
parser.add_argument('--train-query', type=int, default=10,
                            help='number of query examples per training class')

**Comment by ahmetius** [comment]
Hi,

I reduced the number of queries to 6, but still get out of memory error. Could you tell me which pytorch version you were using to run the experiments?

**Comment by ahmetius** [comment]
Setting --train-query', type=int, default=5 works! Thanks for the help!

**Comment by chrysts** [comment]
Did you change  os.environ['CUDA_VISIBLE_DEVICES'] = "0,3" -> os.environ['CUDA_VISIBLE_DEVICES'] = "0,1,2,3"?

My current versions:
PyTorch 0.4.1 / 1.0.1 (I tried in both settings and they work)
Cuda 9.0
Cudnn v7.5.0

I have just run using this setting:
'num_epoch': 80, 'save_epoch': 5, 'train_shot': 15, 'val_shot': 5, 'train_query': 6, 'val_episode': 600, 'val_query': 15, 'train_way': 5, 'test_way': 5, 'save_path': './experiments/exp_1', 'gpu': '0,1,2,3', 'network': 'ResNet', 'head': 'Subspace', 'dataset': 'miniImageNet', 'episodes_per_batch': 8, 'eps': 0.0}

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     48346      C   /usr/bin/python3.6                         13511MiB |
|    1     48346      C   /usr/bin/python3.6                         11211MiB |
|    2     48346      C   /usr/bin/python3.6                         11211MiB |
|    3     48346      C   /usr/bin/python3.6                         11193MiB |
+-----------------------------------------------------------------------------+

**Comment by ahmetius** [comment]
Yes, I have changed that. Furthermore, set_gpu function in your code takes care of that as well. I could get it to run with the following config:
Namespace(dataset='miniImageNet', episodes_per_batch=8, eps=0.1, gpu='4,5,6,7', head='Subspace', network='ResNet', num_epoch=80, save_epoch=5, save_path='/mnt/disks/ssd/dsn_fewshot/Resnet12', test_way=5, train_query=5, train_shot=15, train_way=5, val_episode=600, val_query=15, val_shot=5)

I will let you know if I can reproduce your scores. Thanks for the help!
