### ISSUE TITLE
How to reproduce the reported results?

### ISSUE THREAD

**Issue by buptxiaofeng** [chrysts/dsn_fewshot#10]
I am trying to reproduce the results in the paper, and I tried to run the scripts in the Conv4 dir with default parameters, but the results are not as good as the reported ones in the paper. Could you share the parameters and more training details? That can be very helpful for me and I really appreciate it.

**Comment by chrysts** [comment]
Hi buptxiaofeng,

Thank you for you interest in our work.
We don't have special parameters, there are two ways to get the results like in the paper:
1. Change the pytorch version to 1.1.0.
2. Train with more epochs
