### ISSUE TITLE
The setting of  '--train-shot' in ResNet12/train.py

### ISSUE THREAD

**Issue by gaunzi** [chrysts/dsn_fewshot#12]
Hi! Thanks for the great work.

Does the parameter '--train-shot' in ResNet12/train.py mean K-shot during meta-training?  And when I set this parameter as 1, the network seems to do not converge and the ACC always is 20%, however, the network can be trained successfully when it is 15.

**Comment by chrysts** [comment]
Hi Gaunzi,

Yes, it impacts the training phase. Actually, the mdoel needs more parameters for meta training.

**Comment by gaunzi** [comment]
> Hi Gaunzi,
> 
> Yes, it impacts the training phase. Actually, the mdoel needs more parameters for meta training.

Thanks for your reply~
So,  how do I train the model under the 5w-1s setting?  When the number of shot is 1, should I augment the support sample to 2 ?

**Comment by chrysts** [comment]
The model for ResNet-12 is trained on 5-way 15-shot and evaluate on 5-way 1 shot and 5 shot (without further finetuning using the support samples).
