### ISSUE TITLE
Question about Equation 2 and its implementation

### ISSUE THREAD

**Issue by toooooodo** [chrysts/dsn_fewshot#15]
Hi, thanks for your work, it's very inspiring to me. 
But I‘m confused about how Equation2 is derived. Could you please give me some promts about how this formula is derived? 
And I notice that there is an identity matrix I in this formula, but it seems that the [code implementation](https://github.com/chrysts/dsn_fewshot/blob/master/Conv4/algorithm/subspace_projection.py#L41) does not have it. I also don't quite understand how it's implemented here.
Thanks.

**Comment by chrysts** [comment]
Hi,
Thanks for your interest to our work.
Eq. 2 might look confusing but actually if you multiply every element then it can be reformulated as in Line 41-54.

Cheers

**Comment by toooooodo** [comment]
Thanks for your reply. I understand it now!😁

**Comment by UniStarry** [comment]
Hi, thanks for your work! I'm also confused about the equation(2).
In the paper, (I-Mc)(f(q)-u),while in the code, 
"projected_query_j = torch.bmm(h_plane_j, torch.bmm(torch.transpose(h_plane_j, 1, 2), target_features_expanded))" seems stands for the Mc(f(q)-mu),
besides, "projected_query_j = torch.squeeze(projected_query_j) + mu[j].unsqueeze(0).repeat(batch_size, 1)" adds the class mean mu[j], this is why?
thanks very much!

**Comment by UniStarry** [comment]
I have no questions, thank you very much!
