### ISSUE TITLE
a request

### ISSUE THREAD

**Issue by aheroofchina** [chrysts/dsn_fewshot#16]
Sorry to bother you, is your email still firstname.lastname@anu.edu.au? I can get in touch with you via email, but it keeps failing, I don’t know why。

**Comment by aheroofchina** [comment]
![图片](https://user-images.githubusercontent.com/90619869/174203757-b6281f52-33a6-48b2-8ee6-c9bf35e851bc.png)

**Comment by aheroofchina** [comment]
Please forgive me for leaving you a message here, because I really can't find a way to contact you. I read your paper: meta learning for multi label feed shot classification. I have deep feelings and feel that it can be used in the direction of my research. Therefore, I hope to obtain a code so that I can further understand the details of your paper. If you agree, I hope you can send your paper to jindachuan1997@gmail.com   Thank you for your help. I wish you and your family a healthy and successful career.

**Comment by chrysts** [comment]
Hi, Thanks for you interest to our work.
Firstname and lastname must be replaced with my name on the paper. 
I have sent you an email.
