### ISSUE TITLE
DSN for CUB dataset

### ISSUE THREAD

**Issue by LoveMiki** [chrysts/dsn_fewshot#17]
Hi,
Using your code, i can reproduce the results on your paper.
Then i try to use DSN to train on the CUB-200-2011 dataset, but I got the error "The algorithm failed to converge because the input matrix is ill-conditioned or has too many repeated singular values". 
Are there any solutions to this issue? BTW, I used the common data format of CUB, which contains the raw images with different resolutions.

Thank you in advance.

**Comment by chrysts** [comment]
Hi LoveMiki,

Are you training on 1 shot or 5 shot?
I think that error usually happens when you train with 1 image per class in the support set.

Best,
Chris
