### ISSUE TITLE
CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by SpringUp** [chrysts/dsn_fewshot#3]
Hi!
Thanks for sharing the code.
When running the conv4 experiment using the python train_subspace_discriminative.py --data-path  /home/dsn_fewshot/miniImageNet command, I encountered an error as follows：

acc = count_acc(logits, label)
  File "/home/dsn_fewshot/Conv4/utils.py", line 86, in count_acc
    return (pred == label).type(torch.cuda.FloatTensor).mean().item()
RuntimeError: CUDA error: an illegal memory access was encountered

In debug mode, I locate this error appearing in line 43 in the subspace_projection.py file，that is,
projected_query_j = torch.bmm(h_plane_j, torch.bmm(torch.transpose(h_plane_j, 1, 2), target_features_expanded) , 
and the error is Unable to get repr for＜class‘torch.Tensor‘＞

Could you tell me how to solve this problem?

**Comment by chrysts** [comment]
Hi SpringUp,

I guess you have something wrong when loading your data. I have used several machines and PyTorch versions still working well on my side.
