### ISSUE TITLE
Test on the miniimagenet dataset

### ISSUE THREAD

**Issue by Wang01l** [chrysts/dsn_fewshot#4]
Hello, thanks for your great work first.
When I run the test_subspace_discriminative in Conv4 on the miniimagenet dataset. The result is that:
```
{'data_path': '/media/ubuntu/460CFEF50CFEDEBD/wl/CovaMNet-master/dataset/mini-imagenet/For_FewShot/',
 'gpu': '0',
 'lamb': 5,
 'max_epoch': 600,
 'query': 15,
 'save_epoch': 100,
 'save_path': './save/subspace-5w5sdiscriminative/max-acc.pth',
 'shot': 1,
 'subspace_dim': 0,
 'test_way': 5,
 'train_way': 5}
using gpu: 0
 TEST loss=1.2516 acc=0.4917 maxacc=0.0000
```
I want to know if this result is correct, or what other parameters I need to add during the run.
Thanks in advance for your help.

**Comment by chrysts** [comment]
Hi Wang01l,

Is that the test acc on the validation or test set?

There are two things that you can try:
1. args.subspace_dim=2
2. args.lamb = 0.01
