### ISSUE TITLE
parameters for the protonet (resnet12)is what? I use the default config to train, the5way 1 shot for cifarfs accuracy is just 63?

### ISSUE THREAD

**Issue by xue19890510** [chrysts/dsn_fewshot#5]
could you tell me the config for the  protonet for the tiredimagenet and cifar fs ,I can't the the 5 way 1 shot accuracy  as the papers,use the protonet (backbone is resnet 12)?

**Comment by chrysts** [comment]
Hi Xue,

You can try to train on tieredimagenet with 10-shot (4 gpus) and cifar-fs with 5-shot (1 gpu). The other params are the same.
