### ISSUE TITLE
tieredImagenet loader meet a problem ,the dict don't have attribute labels ,it have label_general and label_specific?

### ISSUE THREAD

**Issue by xue19890510** [chrysts/dsn_fewshot#6]
1 As the tilte , I run the program for the tieredImagenet ,but I met the problem at the data_train['labels'] , then i  debug and find that the data_train don't have labels attribute, but it have label_general and label_specific, do you meet the problem or you have any ideas about this? by the way ,the data you provide is about 12GB,  I found another 23GB data and it works. Why the data you give have the   label_general and label_specific problem?

2 thank you for your work, the mini-imagenet and the tieredImagenet  you give the learning rate, could you give the learning rate for cifar fs.
@chrysts  look   forward you reply sincerly!

**Comment by chrysts** [comment]
Hi Xue,

1. Where did you download the tieredImageNet? This version is the one I downloaded from the MetaOpt paper (CVPR2019).


2. CIFAR_FS learning rate, please try this: 

lambda_epoch = lambda e: 1.0 if e < 20 else (0.04 if e < 40 else 0.01 if e < 50 else (0.001 if e < 60 else (0.0001)))

**Comment by xue19890510** [comment]
Thank you for your reply ,
1. I hava download the wrong tieredImageNet, sorry !
2. I wirll try the learning rate, thank you
