### ISSUE TITLE
I trained the tired-Imagnet with protonet,used resnet12,bu the accuracy test is only 78.4,less than 80,so  whats the parameters?

### ISSUE THREAD

**Issue by xue19890510** [chrysts/dsn_fewshot#7]
Thank you for your reply for the two issues.
I have another question, I used the 10-shot 5-way to train, and tested the 5-shot, but only get 78.4,could you tell me the paramerts, like the learning  rates, my learning rates is lambda_epoch = lambda e: 1.0 if e < 20 else (0.012 if e < 45 else 0.0052 if e < 59 else (0.00054 if e < 68 else (0.00012))),
Are there any other paramerts need to ajust? or how to train and test to get the 80.00 accuracy for the tired-imagnet.
Thank you very much.

**Comment by chrysts** [comment]
Hi Xue,

What is the query number that you used?
