### ISSUE TITLE
Could you please release the pre-trained conv4 and resnet12 model of miniImageNet？

### ISSUE THREAD

**Issue by IceLeeCool** [chrysts/dsn_fewshot#9]
Hey，
The work of your team is very impressive, and i want to do some contrast experiments with your approach, could you please give out the link to the pre-trained conv4 model of miniImageNet?

Hope to receive your reply soon, thank you.

**Comment by chrysts** [comment]
[max-acc.pth.zip](https://github.com/chrysts/dsn_fewshot/files/6934751/max-acc.pth.zip)
Please see the attachment.

**Comment by JulieCarlon** [comment]
> [max-acc.pth.zip](https://github.com/chrysts/dsn_fewshot/files/6934751/max-acc.pth.zip)
> Please see the attachment.

Hi, could you please also upload the pre-trained resnet-12 model of CIFAR100 dataset? 
Looking forward to your reply. Thank you so much!

**Comment by chrysts** [comment]
Hi JulieCarlon,

Unfortunately, I do not have the pretrained resnet-12 model at the moment. But you can see the recent few shot learning methods on github that have more pwoerful pretrained networks.
